server:
  port: 8088
  connection-timeout: 100

  #测试主库
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
          master:
             url: jdbc:mysql://&&&&&&&&&&&&&&&&&&&:3306/tcc_order?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
             username: admin
             password: admin
             validation-query: SELECT 1
             initial-size: 5
             max-active: 100
             min-idle: 5
             max-wait: 6000
             remove-abandoned: true
             remove-abandoned-timeout-millis: 1800
             time-between-eviction-runs-millis: 60000
             min-evictable-idle-time-millis: 25200000
             filters: wall
             stat-view-servlet:
                                 enabled: false
             use-global-data-source-stat: true
          slave:
             url: jdbc:mysql://################:3306/tcc_order?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&rewriteBatchedStatements=true
             username: admin
             password: admin
             validation-query: SELECT 1
             initial-size: 5
             max-active: 100
             min-idle: 5
             max-wait: 6000
             remove-abandoned: true
             remove-abandoned-timeout-millis: 1800
             time-between-eviction-runs-millis: 60000
             min-evictable-idle-time-millis: 25200000
             filters: wall
             stat-view-servlet:
                                 enabled: false
             use-global-data-source-stat: true
  redis:
          database: 0
          host: 
          port: 6379
          password:
          timeout: 0
          pool:
             max-active: 8
             max-wait: -1
             max-idle: 8
             min-idle: 0
logging:
  config: classpath:log4j2.xml
